networks:
    nodesystemnet:
        external: true

services:
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        ports:
            - "3000:9090"
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        networks:
            nodesystemnet:
                ipv4_address: "172.72.15.10"

    grafana:
        image: grafana/grafana
        container_name: grafana
        ports:
            - "3001:3000"
        depends_on:
            prometheus:
                condition: service_started
        networks:
            nodesystemnet:
                ipv4_address: "172.72.15.11"