global:
    scrape_interval: 15s
    scrape_timeout: 10s
    evaluation_interval: 15s
    
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
scrape_configs:
- job_name: node-develop
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /debug/metrics/prometheus
  scheme: http
  static_configs:
  - targets:
    - 172.15.1.10:6060

- job_name: node-linea
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /debug/metrics/prometheus
  scheme: http
  static_configs:
  - targets:
    - 172.15.0.11:6060